import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/landing/Home.module.css'
import titleMainPic from "@/public/pics/titleMain.png"
import Cookies from 'js-cookie';

export default function Home(props:any) {

  return (
    <>

      <Head>
        <title>Crypto Dorea: next generation crypto loyalty program</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className='container max-w-full'>

          <div className='grid grid-cols-2 gap-1 mt-10'> 
            <div className='w-12/12 pl-28'>
              <p className={`${styles.titleMain} text-6xl`}>
                Crypto Giveaways <br />
                for hyping users
              </p>
              <p>
                create crypto loyalty program for your business
              </p>
              <p>
                <span>get paid on:</span>
                <span></span>
              </p>
              <div>
                  <div></div>
              </div>
            </div>
            <div className='w-12/12 pl-5 flex flow-row'>
              <div>
                <Image className={styles.titleMainPic} src={titleMainPic} alt='no title image available' />  
              </div>
            </div>
          </div>

        </div>


      </main>

    </>
  )
}

export async function getServerSideProps() {

  return {
    props:{}
  }
  
}

