import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Cookies from 'js-cookie';
import jwt from 'jsonwebtoken';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props:any) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className='font-bold'>
                
              Home page

              
    
          </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {

  const secretKey:any = process.env.JwtSecretKey
  
  return {
    props:{secretKey}
  }
  
}